const {
    ADD_NOTE,
    UPDATE_NOTE,
    DELETE_NOTE,
    GET_USER_NOTES,
    GET_ALL_NOTES
} = require("../../../src/notes/endPoints");
const {
    UPDATE_USER,
    UPDATE_PASSWORD,
    RESET_PASSWORD,
    DEACTIVATE_USER,
    BLOCKED_USER,
    ADD_ADMIN,
    GET_ALL_ADMINS,
    DELETE_ADMIN,
    LOGOUT
} = require("../../../src/users/endPoints");

module.exports = [UPDATE_USER, UPDATE_PASSWORD, RESET_PASSWORD, DEACTIVATE_USER, BLOCKED_USER, ADD_ADMIN, GET_ALL_ADMINS,
    DELETE_ADMIN, ADD_NOTE, UPDATE_NOTE, DELETE_NOTE, GET_USER_NOTES, GET_ALL_NOTES, LOGOUT
]