const UPDATE_USER = "user:UPDATE_USER"
const UPDATE_PASSWORD = "user:UPDATE_PASSWORD"
const UPDATE_EMAIL = "user:UPDATE_EMAIL"
const RESET_PASSWORD = "user:RESET_PASSWORD"
const DELETE_ADMIN = "admin:DELETE_ADMIN"
const GET_ALL_ADMINS = "admin:GET_ALL_ADMINS"
const DEACTIVATE_USER = "user:DEACTIVATE_USER"
const BLOCKED_USER = "user:BLOCKED_USER"
const ADD_ADMIN = "admin:ADD_ADMIN"
const UPDATE_ADMIN = "admin:UPDATE_ADMIN"
const GET_USER = "user:GET_USER"
const LOGOUT = "user:LOGOUT"

module.exports = {
    UPDATE_USER,
    DELETE_ADMIN,
    GET_ALL_ADMINS,
    DEACTIVATE_USER,
    BLOCKED_USER,
    UPDATE_PASSWORD,
    RESET_PASSWORD,
    ADD_ADMIN,
    UPDATE_ADMIN,
    GET_USER,
    UPDATE_EMAIL,
    LOGOUT
}